# Generated by Django 5.0 on 2024-01-03 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('driving_experience', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('total_rides', models.PositiveIntegerField(default=0)),
                ('earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('availability_status', models.BooleanField(default=True)),
                ('last_updated_location', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('van', 'Van'), ('motorcycle', 'Motorcycle')], max_length=10)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('license_plate_number', models.CharField(max_length=10, unique=True)),
                ('insurance_expiry_date', models.DateField()),
                ('fitness_certificate_expiry_date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='vehicle_images')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Driver.driver')),
            ],
        ),
    ]
