# Generated by Django 5.0 on 2024-01-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0002_alter_driver_driving_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
