# Generated by Django 5.0 on 2024-01-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0003_alter_driver_address_alter_driver_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
