# Generated by Django 5.0 on 2024-03-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0005_rename_make_vehicle_company_made_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='year',
            new_name='age',
        ),
    ]
