# Generated by Django 5.0 on 2024-03-26 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0010_trip_booking_ticket_vehicle_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='available_seat',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='TripPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.trip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.vehicle')),
            ],
        ),
    ]
