# Generated by Django 5.0 on 2024-03-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0011_booking_price_alter_vehicle_available_seat_tripprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='trips',
        ),
        migrations.RemoveField(
            model_name='tripprice',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='tripprice',
            name='vehicle',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='available_seat',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='TripPrice',
        ),
    ]
