# Generated by Django 5.0 on 2024-03-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0013_trip_booking_ticket_tripprice_booking_tripprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='from_location',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_location',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
