# Generated by Django 5.0 on 2024-03-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0014_alter_trip_from_location_alter_trip_to_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='tripprice',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='tripprice',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='TripPrice',
        ),
    ]
