# Generated by Django 5.0 on 2024-03-28 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0015_remove_ticket_booking_remove_tripprice_trip_and_more'),
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=100, unique=True)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_passengers', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passenger.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_file', models.FileField(upload_to='tickets/')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Driver.booking')),
            ],
        ),
        migrations.CreateModel(
            name='TripPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.trip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='tripprice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.tripprice'),
        ),
    ]
