# Generated by Django 5.0 on 2024-03-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0016_trip_booking_ticket_tripprice_booking_tripprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(default='JNKKTM', max_length=100, unique=True),
        ),
    ]
