# Generated by Django 5.0 on 2024-03-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0017_alter_trip_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripprice',
            name='trip_price_id',
            field=models.CharField(default='POKKATABC123', max_length=100),
        ),
    ]
