# Generated by Django 5.0 on 2024-03-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0018_tripprice_trip_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripprice',
            name='trip_price_id',
            field=models.CharField(default='POKKATABC123', max_length=100, unique=True),
        ),
    ]
