# Generated by Django 5.0 on 2024-04-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0022_alter_ticket_ticket_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fitness_certificate_expiry_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_expiry_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
